### PR TITLE
fix: fix memory write

### PR DESCRIPTION
**Pull request by GCdePaula**
This is a work in progress, the tests aren't working yet. The purpose was to show what I had in mind for reading memory. Let me know what you think, if it makes sense we can move on to fixing the tests and merge.

### CODE REVIEW

**Comment by GCdePaula** [comment]
Do we know the actual value of the leaf before the write, or only its hash?
@diegonehab @mpernambuco

**Comment by stephenctw** [comment]
I think this can work. From the current json log files, I only see the hash of the leaf before the write, not the value.

**Comment by mpernambuco** [comment]
Hi @GCdePaula 
For write accesses, he `read` leaf data was not present in the uarch json logs. It is required for computing the written leaf, as per the discussion in the original PR.
 I've made this change to the logs to always include the read leaf data
https://github.com/cartesi/machine-emulator/pull/259/commits/6cd489408fcb605781c5832d224871be255b8464
The PR https://github.com/cartesi/machine-solidity-step/pull/68 was also updated to take the new format into consideration.

**Review by mpernambuco — APPROVED** [review]
Heck YES!

**Pull request merged**
